import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Header from "./../component/HomeComponent/Header";
import Founder from "./../component/HomeComponent/Founder";
import Company from '../component/HomeComponent/Company';
import Advertisement from '../component/HomeComponent/Advertisement';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Basem Group</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

      </Head>

      <Header />
      <Founder />
      <Company />
      <Advertisement />



    </div>
  )
}
